---
- name: Rainbond | Prepare Up Node
  template:
    src: nodeup.sh.j2
    dest: /tmp/install/nodeup.sh
    mode: 0777

- name: Rainbond | Up Node 
  shell: "bash /tmp/install/nodeup.sh > /tmp/install/nodeup.log"
  register: nodeup_task_result
  until: nodeup_task_result is succeeded
  retries: 5

- name: Copy image push script
  template:
    src: pushimage.sh.j2
    dest: /tmp/install/pushimage.sh
    mode: 0777

- name: Copy check insecure registries
  template:
    src: check_registries.sh.j2
    dest: /tmp/install/check_registries.sh
    mode: 0777

- name: check certs dir
  file: name=/etc/docker/certs.d/goodrain.me/ state=directory

- name: Copy goodrain.me crt
  shell: "docker cp rbd-gateway:/var/run/nginx/conf/rainbond/ssl/server.crt /etc/docker/certs.d/goodrain.me/ca.crt"

- name: Rainbond | Check local image registry
  shell: "bash /tmp/install/check_registries.sh > /tmp/install/check_registries.log"

- name: Rainbond | Check check_ok
  stat: path="/opt/rainbond/.init/goodrain.me.ok"
  register: check_goodrainme_done

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting Pushing images to local image registry"
  when: check_goodrainme_done.stat.isreg is defined

- name: Rainbond | Push images to local image registry
  shell: "bash /tmp/install/pushimage.sh > /tmp/install/pushimage.log"
  register: pushimage_task_result
  until: pushimage_task_result is succeeded
  retries: 5
  when: check_goodrainme_done.stat.isreg is defined