---
- name: Check http::proxy in /etc/apt/apt.conf
  raw: grep -qsi 'Acquire::http::proxy' /etc/apt/apt.conf
  register: need_http_proxy
  failed_when: false
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  environment: {}
  when:
    - http_proxy is defined

- name: Add http_proxy to /etc/apt/apt.conf if http_proxy is defined
  raw: echo 'Acquire::http::proxy "{{ http_proxy }}";' >> /etc/apt/apt.conf
  become: true
  environment: {}
  when:
    - http_proxy is defined
    - need_http_proxy.rc != 0

- name: Check https::proxy in /etc/apt/apt.conf
  raw: grep -qsi 'Acquire::https::proxy' /etc/apt/apt.conf
  register: need_https_proxy
  failed_when: false
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  environment: {}
  when:
    - https_proxy is defined

- name: Add https_proxy to /etc/apt/apt.conf if https_proxy is defined
  raw: echo 'Acquire::https::proxy "{{ https_proxy }}";' >> /etc/apt/apt.conf
  become: true
  environment: {}
  when:
    - https_proxy is defined
    - need_https_proxy.rc != 0

- name: rm ubuntu lxd & ufw package
  apt: 
    name: 
      - ufw
      - lxd
      - lxd-client
      - lxcfs
      - lxc-common
      - nscd
      - dnsmasq
    state: absent
  tags: prepare

- name: install ubuntu package
  apt: 
    name:
      - nfs-common          
      - conntrack           
      - jq                  
      - socat               # port forwarding
      - bash-completion     
      - rsync               
      - ipset
      - ipvsadm
      - net-tools
      - expect
    update_cache: yes
    autoclean: yes
    state: latest

- name: configuration ulimits
  lineinfile:
    dest: /etc/profile
    regexp: "ulimit -SHn"
    line: "ulimit -SHn 65535"

- name: prepare journal log
  file: name={{ item }} state=directory
  with_items:
  - "/etc/systemd/journald.conf.d"
  - "/var/log/journal"

- name: Optimize the setting of journal logs
  template: src=95-k8s-journald.conf.j2 dest=/etc/systemd/journald.conf.d/95-k8s-journald.conf

- name: restart journald
  service: name=systemd-journald state=restarted
