---
- name: Hosts | populate rainbond into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {{hostvars[groups['master'][0]]['ip']}}  {{ rainbond_domain }}
    state: present
    create: yes
    backup: yes
    marker: "# Rainbond hosts {mark}"

- import_tasks: offline.yml
  when: install_type == "offline"

- import_tasks: check.yml

- import_tasks: debian.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- import_tasks: setup-pipelining.yml

- import_tasks: common.yml 