---
- name: Offline | Check offline repo
  stat: path=/opt/rainbond/.init/.offline
  register: offline_repo

- name: Offline | Add CentOS Repository
  yum_repository:
    name: local
    description: rpm local
    file: rainbond
    baseurl: http://repo.goodrain.me/rpm/centos/7/
  when: ansible_distribution == "CentOS" and offline_repo.stat.isreg is not defined

- name: Offline | yum-clean-metadata
  command: yum clean all
  args:
    warn: no
  when: ansible_distribution == "CentOS"