---
- name: Storage | copy check storage
  template:
    src: check_storage.sh.j2
    dest: /tmp/check_storage.sh
    mode: 0777

- name: Storage | run check storage
  shell: "bash /tmp/check_storage.sh"

- name: Storage | check grdata
  stat: path=/tmp/.grdata.init
  register: check_grdata

- import_tasks: config.yml
  when: check_grdata.stat.isreg is not defined