---
- name: DB | run if image is pulled
  command: /usr/local/bin/check_img db

- name: DB | check if image is pulled
  stat: path="/tmp/install/check_db_img"
  register: check_db_img

- name: DB | pull db from goodrain.me
  shell: "docker pull goodrain.me/{{ rbd_db_image }}"
  when: check_db_img.stat.isreg is not defined

- name: DB | prepare dir 
  file: name={{ item }} state=directory
  with_items:
    - "{{ rbd_dir }}/etc/rbd-db/conf.d"

- name: DB | Copy DB Role
  template:
    src: db.role.j2
    dest: "{{ node_role_dir }}/db.yaml"

- name: DB | Copy DB Conf
  template:
    src: my.cnf.j2
    dest: "{{ rbd_dir }}/etc/rbd-db/mysqld.cnf"

- name: DB | Copy DB Init Script
  template:
    src: charset.cnf.j2
    dest: "{{ rbd_dir }}/etc/rbd-db/conf.d/charset.cnf"

- name: Add Reset Superadmin tools
  template:
    src: reset_superadmin.sh.j2
    dest: "{{ rbd_dir }}/etc/tools/bin/reset_superadmin.sh"